### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by mallowigi** [jaysuz/material-dev-tools#1]
As the maintainer of the Material Theme UI for Jetbrains, I thank you for that. However some remarks:

- First of all, I don't know why are there remnants of the Darker theme in the Oceanic one (#242424). You should use the Contrast color instead.
- Also, you could allow to switch themes via an options panel, just like the plugin.

If you managed to do that, I'll include this plugin in the documentation site and the README. Great work!

**Comment by jaysuz** [comment]
Thank you very much for your comment, I'm flattered! I will gladly try and implement your suggestions as soon as possible.

**Comment by mallowigi** [comment]
I saw you fixed the issue with the Dark colors, good job!
