### ISSUE TITLE
can not work in chrome73

### ISSUE THREAD

**Issue by TuKun33** [jaysuz/material-dev-tools#2]

**Comment by jaysuz** [comment]
@TuKun33, could you please elaborate? On my machine (Macbook running Chrome 73) it still works as expected. I have, however, noticed that the Chrome team must have changed their selection highlight styles, so thank you for that.

Are you sure you have correctly followed the instructions to enable custom developer tools themes?

**Comment by TuKun33** [comment]
![image](https://user-images.githubusercontent.com/22310931/54741726-469b4980-4bfa-11e9-835c-5af481595311.png)

![image](https://user-images.githubusercontent.com/22310931/54741682-29667b00-4bfa-11e9-88cd-f2d4d2b19c7b.png)

Anything else ?

**Comment by jaysuz** [comment]
This theme is meant as a replacement for the native dark theme of the Chrome devtools, so you will have to switch to that one for it to be applied (see screenshot below). I realise now that this requirement is not mentioned prominently enough, so I'll update the readme accordingly.

<img width="1114" alt="Screen Shot 2019-03-21 at 11 29 40" src="https://user-images.githubusercontent.com/16406401/54746693-1ee1bc80-4bcd-11e9-9326-31c76f6a9117.png">

**Comment by TuKun33** [comment]
good! thinks
